import { InstrumentDefinition } from "./types";

export const instrumentDefinitions: InstrumentDefinition[] = [
  {
    id: "xau-usd",
    name: "Gold",
    symbol: "XAUUSD",
    displaySymbol: "XAU / USD",
    category: "metal",
    currency: "USD",
    basePrice: 2650.0,
    volatility: 15.0,
    unit: "TROY OZ",
  },
  {
    id: "xag-usd",
    name: "Silver",
    symbol: "XAGUSD",
    displaySymbol: "XAG / USD",
    category: "metal",
    currency: "USD",
    basePrice: 31.5,
    volatility: 0.5,
    unit: "TROY OZ",
  },
  {
    id: "xpt-usd",
    name: "Platinum",
    symbol: "XPTUSD",
    displaySymbol: "XPT / USD",
    category: "metal",
    currency: "USD",
    basePrice: 985.0,
    volatility: 12.0,
    unit: "TROY OZ",
  },
  {
    id: "btc-usd",
    name: "Bitcoin",
    symbol: "BTCUSD",
    displaySymbol: "BTC / USD",
    category: "crypto",
    currency: "USD",
    basePrice: 95000.0,
    volatility: 1500.0,
  },
  {
    id: "eth-usd",
    name: "Ethereum",
    symbol: "ETHUSD",
    displaySymbol: "ETH / USD",
    category: "crypto",
    currency: "USD",
    basePrice: 3200.0,
    volatility: 80.0,
  },
  {
    id: "eur-usd",
    name: "EUR / USD",
    symbol: "EURUSD",
    displaySymbol: "EUR / USD",
    category: "fx",
    currency: "USD",
    basePrice: 1.08,
    volatility: 0.005,
    unit: "MAJOR FX",
  },
  {
    id: "gbp-usd",
    name: "GBP / USD",
    symbol: "GBPUSD",
    displaySymbol: "GBP / USD",
    category: "fx",
    currency: "USD",
    basePrice: 1.27,
    volatility: 0.006,
    unit: "MAJOR FX",
  },
  {
    id: "usd-cad",
    name: "USD / CAD",
    symbol: "USDCAD",
    displaySymbol: "USD / CAD",
    category: "fx",
    currency: "CAD",
    basePrice: 1.39,
    volatility: 0.005,
    unit: "MAJOR FX",
  },
];
